### ISSUE TITLE
import the following entry points when i need to access many languages

### ISSUE THREAD

**Issue by ZhangTomLiang** [FIameCaster/prism-code-editor#36]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/69b46a5b-0060-474a-8b74-e76e5cfc6d29">

**Comment by FIameCaster** [comment]
You can import `prism-code-editor/prism/languages/common` for [42 common languages](https://github.com/FIameCaster/prism-code-editor/blob/main/package/src/prism/languages/common.js), or `prism-code-editor/prism/languages` for all languages like you've done.

I'm not sure what your issue is, could you specify?

**Comment by ZhangTomLiang** [comment]
I tried your advice，but seems not work.

import 'prism-code-editor/prism/languages/common';
or 
import 'prism-code-editor/prism/languages';

the website client will be get error, please see the below.

chunk-4LSTX5LK.js?v=dbf9d462:209 Uncaught TypeError: Cannot read properties of undefined (reading 'markup-bracket')
    at chunk-4LSTX5LK.js?v=dbf9d462:209:33

**Comment by ZhangTomLiang** [comment]
<img width="970" alt="image" src="https://github.com/user-attachments/assets/d29838af-0ed9-4305-8dcf-eebba82bf1ec">
