### ISSUE TITLE
Angular 18.2.0 SSG integration error

### ISSUE THREAD

**Issue by IPdotSetAF** [FIameCaster/prism-code-editor#38]
hi.

i am trying to integrate this library in an angular SSG project, I followed [SpringWolf](https://github.com/springwolf/springwolf-core/blob/master/springwolf-ui/src/app/components/code/prism-editor.component.ts) implementation , but I get the following error,
```
document is not defined
    at eval (.....\CodeChef\.angular\cache\18.2.9\CodeChef\vite\deps_ssr\chunk-FA6WLLQY.js:205:18)
    at async instantiateModule (file:///........./CodeChef/node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52914:5

```
even when I follow the Basic setup provided in the prism-code-editor docs, I get the same error.

any tip is appreciated.

[repo with the mentioned error](https://github.com/IPdotSetAF/CodeChef/tree/prism-code-editor)

**Comment by FIameCaster** [comment]
SSG runs the app in Node. Since most entry points of prism code editor uses browser globals in module scope, it will error when running in Node.

This is fixed in v4 which is a WIP. You can install the beta with `npm i prism-code-editor@beta`. The beta should fix your issue, but you might want to wait for the full release.

**Comment by IPdotSetAF** [comment]
Thanks for quick response.
I'll give it a try and let you know.

**Comment by IPdotSetAF** [comment]
I tried the v4 beta, worked smoothly in the first try 👍 

If there is anything i can help with on the v4, testing or development, feel free to hit me up.
